<template>
  <Head>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Rubik:wght@400..700&display=swap"
    />
    <title>Wunderbar Website</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main
    class="relative h-screen w-screen snap-y snap-mandatory overflow-x-hidden"
  >
    <Navbar :backgroundColor="green" />
    <section
      class="flex min-h-full w-full snap-start snap-always flex-row items-center justify-start bg-hero_image_mobile bg-cover before:absolute before:h-screen before:w-screen before:bg-white before:bg-opacity-30 before:content-[''] md:bg-hero_image md:before:content-none"
    >
      <div class="z-20 mb-[40vh] ml-[3vh] md:mb-10 md:ml-36">
        <h1
          class="bg-[#DBD7D4] bg-opacity-60 px-5 py-5 font-title text-5xl md:text-8xl"
        >
          WUNDERBAR
        </h1>
        <div class="flex justify-between">
          <h2
            class="bg-[#DBD7D4] bg-opacity-60 px-5 py-5 font-body text-sm font-medium tracking-[.4em] md:text-xl"
          >
            HANDMADE SOAP
          </h2>
          <div
            class="mr-[30px] mt-7 grow border-t-2 border-black md:ml-8 md:mr-0 md:mt-8"
          ></div>
        </div>
      </div>
    </section>

    <section
      class="flex min-h-full w-full snap-start snap-always flex-col justify-center bg-white lg:flex-row"
    >
      <div
        class="flex max-h-[1200px] max-w-[1200px] flex-col items-center lg:mt-[5%] lg:flex-row"
      >
        <img
          src="/soapstack.png"
          alt="Stack of Soap"
          class="mt-[15%] flex max-w-[65%] lg:ml-[5%] lg:mr-[15%] lg:mt-[0%] lg:max-h-[65%] lg:max-w-[35%]"
        />
        <div
          class="mx-[12%] mt-[6%] flex flex-col items-start justify-center lg:mx-[2%] lg:mt-[4%] lg:w-[100vh]"
        >
          <h1
            class="mb-[4%] font-title text-mobile_title lg:mb-[6%] lg:text-bigscreen_title"
          >
            HANDMADE SOAP
          </h1>
          <p
            class="mb-[10%] font-body text-mobile_body lg:max-w-lg lg:text-bigscreen_body"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porta
            laoreet enim, sit amet cursus neque vulputate ac. Fusce sem ante,
            mollis vitae mollis eu, cursus at elit. Integer lobortis et diam a
            sodales. Quisque semper purus leo, sed convallis turpis mollis
            quis..
          </p>
          <button
            class="mb-[5%] rounded-3xl bg-black px-6 py-1 font-body text-mobile_body font-medium tracking-widest text-white lg:mt-4 lg:text-bigscreen_body"
          >
            <!-- <Link href="/store">SHOP NOW</Link> -->
            <router-link to="/store">SHOP NOW</router-link>
          </button>
        </div>
      </div>
    </section>

    <section
      id="about_page"
      class="flex min-h-full w-full snap-start snap-always flex-col items-center justify-center bg-white"
    >
      <img
        class="hidden max-h-[500px] w-full min-w-[460px] md:block"
        src="/soaprow.png"
        alt="Soaprow"
      />
      <img
        class="mt-[5%] max-h-[500px] w-full md:hidden"
        src="/mobile_soaprow.png"
        alt="Soaprow"
      />
      <div
        class="relative mx-[12%] mt-[7%] flex flex-col md:flex-row lg:ml-[16%] lg:mt-[1%]"
      >
        <h1
          class="flex max-w-[450px] items-center font-title text-mobile_title lg:text-bigscreen_title"
        >
          What do you know about soap?
        </h1>
        <div class="flex flex-col">
          <p
            class="flex max-w-lg pt-4 font-body text-mobile_body lg:pt-8 lg:text-bigscreen_body"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur.
          </p>
          <button
            class="mt-[8%] flex max-w-fit rounded-3xl bg-black px-6 py-1 font-body text-mobile_body font-medium tracking-widest text-white lg:text-bigscreen_body"
          >
            <!-- <Link href="/about">READ MORE</Link> -->
            <router-link to="/about">READ MORE</router-link>
          </button>
        </div>
      </div>
    </section>

    <section
      id="gallery_page"
      class="flex min-h-full w-full snap-start snap-always flex-col items-center justify-center bg-white"
    >
      <img
        class="mt-[100px] hidden w-[80%] max-w-[80%] md:block"
        src="/soapgallery2.png"
        alt="Soapgallery"
      />
      <img
        class="mt-[2vh] h-[65vh] px-[12%] md:hidden"
        src="/big_soaprow_mobile.png"
        alt="Soapgallery"
      />
      <button
        class="mr-[23%] mt-[10%] flex max-w-fit rounded-3xl bg-black px-4 py-1 font-body text-mobile_body font-medium tracking-widest text-white md:relative md:left-[280px] md:top-[-68px] md:z-10 md:mt-12 lg:text-bigscreen_body"
      >
        <router-link to="/gallery">EXPLORE GALLERY</router-link>
        <!-- <Link href="/gallery">EXPLORE GALLERY</Link> -->
      </button>
    </section>

    <section
      id="contact_page"
      class="flex min-h-full w-full snap-start snap-always flex-col items-center justify-between bg-outro_image bg-cover before:absolute before:h-screen before:w-screen before:bg-white before:bg-opacity-30 before:content-['']"
    >
      <div class="z-10 h-[16vh] w-full bg-white"></div>
      <div
        class="z-10 flex h-[40vh] min-h-[300px] w-[160vh] max-w-[100%] flex-col items-start justify-center bg-white bg-opacity-60 px-[12%] lg:h-[30vh] lg:pl-[20%]"
      >
        <h1 class="z-20 font-title text-mobile_title lg:text-bigscreen_title">
          CONTACT PAGE
        </h1>
        <p class="mt-8 font-body text-mobile_body lg:text-bigscreen_body">
          If you have any questions you can reach us at: wunderbarsoap@gmail.com
        </p>
        <button
          class="mt-8 flex max-w-fit rounded-3xl bg-black px-6 py-1 font-body text-mobile_body font-medium tracking-widest text-white lg:text-bigscreen_body"
        >
          EMAIL US
        </button>
      </div>
      <div class="z-10 flex h-[16vh] w-full bg-white"></div>
    </section>
  </main>

  <!-- <Navbar :backgroundColor="green" />
  <div class="w-full min-h-96 flex flex-col justify-center items-center">
    <h1
      class="w-40 text-white bg-slate-500 p-4 rounded-full shadow-lg animate-bounce"
    >
      HALLO
    </h1>
  </div> -->
</template>

<script>
import Navbar from "../components/Navbar.vue";

export default {
  name: "Home",
  components: {
    Navbar,
  },
};
</script>

<style>
</style>